version: "3.8"

services:
  web-app:
    build: ./web_app
    container_name: guess-that-pokemon
    image: vitarose/guess-that-pokemon
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - MONGODB_DATABASE=PokemonDB
      - MONGODB_COLLECTION=PokemonCollection
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    build: ./mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: