version: "3"
services:
  mongodb:
    build: ./mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=PokemonDB
      - MONGODB_COLLECTION=PokemonCollection
    volumes:
      - mongodb-data:/data/db

  web_app:
    build: ./web_app
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DATABASE=PokemonDB
      - MONGODB_COLLECTION=PokemonCollection

volumes:
  mongodb-data:
