# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy to Digital Ocean

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Web-App Docker Image
        run: |
        docker build -f web_app/Dockerfile -t capks/guess_that_pokemon:latest ./web_app
        docker push capks/guess_that_pokemon:latest

      - name: Build and Push MongoDB Docker Image
        run: |
        docker build -f mongodb/Dockerfile -t capks/pokemonmongodb:latest ./mongodb
        docker push capks/pokemonmongodb:latest

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              cd 4-containerized-app-exercise-sst4/
              docker container prune -f
              docker image prune -f
              docker volume prune -f
              docker-compose pull
              docker-compose down
              docker-compose up -d
            else
              echo "Won't deploy if not on main."
            fi
